# 第一关节
- joint: 1
  alpha: 0
  a: 0
  d: 0.1535
  theta: 0
  qlim: [-135, 135]

# 第二关节
- joint: 2
  alpha: -pi / 2
  a: 0.055
  d: 0
  theta: -pi / 2
  qlim: [-90, 90]

# 第三关节
- joint: 3
  alpha: 0
  a: 0.16072
  d: 0
  theta: 0
  qlim: [-90, 45]

# 第四关节
- joint: 4
  alpha: -pi / 2
  a: 0
  d: 0.2205
  theta: 0
  qlim: [-160, 160]

# 第五关节
- joint: 5
  alpha: pi / 2
  a: 0
  d: 0
  theta: pi / 2
  qlim: [-209, 29]

# 第六关节
- joint: 6
  alpha: pi / 2
  a: 0
  d: -0.045
  theta: 0
  qlim: [-180, 180]